#!/bin/sh

amount="$( echo $1 | tr -d '%' )"


case "${2}" in
	system | "")
        default_sink="$( pactl get-default-sink )"

		pactl set-sink-volume $default_sink "${amount}%"
		notify-send -h int:value:"$( pactl get-sink-volume $default_sink | awk '{ print $5 }' | sed 's/%//' )" 'system volume'
		#pkill -RTMIN+1 dwmblocks
	;;
	media )
		playerctl volume "${amount}"
		notify-send -h int:value:"$( mpc volume | awk -F ': ' '{print $2}' | sed 's/%//' )" 'media volume'
	;;
esac

