#!/bin/sh

#remap caps lock to escape
setxkbmap -option "caps:escape"

#remap menu to super
xmodmap -e 'keycode 135=Super_L'
#increase text cursor speed
xset r rate 300 35

#enable autorepeat on insert and pause
xset r 118
xset r 127
