#!/bin/sh

# battery percentage. green bar if charging, red bar if low

low=10
stat=$( cat /sys/class/power_supply/BAT0/status )
percent=$( cat /sys/class/power_supply/BAT0/capacity )
#o="$([ $stat = Discharging ] && echo '%' || echo '⸱')"


if [ $stat != Discharging ]; then
	f='4'
	b='3'
elif (( "$percent" <= "$low" )); then
	f='6'
	b='6'
else
	f='2'
	b='3'
fi

sb_bar "$percent" "$percent%" -l '5' -f "$f" -b "$b"
