#!/bin/bash

# get average cpu freq

echo "AVG $(awk '/MHz/ { print $4 }' /proc/cpuinfo | awk '{for (i=1;i<=NF;++i) {sum+=$i; ++n}} END {printf int(sum/n)}' )Mhz"
#echo "MAX $(awk '/MHz/ { print $4 }' /proc/cpuinfo | awk '{for (i=1;i<=NF;++i) {if( $i>n ) n=$i; }} END {printf int(n)}' )Mhz"
